name: Build Android (APK)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Create Android platform
        run: flutter create . --platforms=android

      - name: Add Internet permission
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if ! grep -q 'uses-permission android:name="android.permission.INTERNET"' "$MANIFEST"; then
            sed -i 's#<application#<uses-permission android:name="android.permission.INTERNET"/>\\n    <application#' "$MANIFEST"
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wa_nux_android_apk
          path: build/app/outputs/flutter-apk/app-release.apk
